# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.webservice.action_listener:
        class: AppBundle\EventListener\WsListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ["@doctrine.orm.entity_manager", "@logger"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }